// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDSsc3njbOIOKj25dRPMLpHAd_yoA92o',
    appId: '1:761481068514:web:2339db487220e9e71cc3bb',
    messagingSenderId: '761481068514',
    projectId: 'dimensions-spiralone',
    authDomain: 'dimensions-spiralone.firebaseapp.com',
    storageBucket: 'dimensions-spiralone.appspot.com',
    measurementId: 'G-QKVX5DYTCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPwzZNWDCP_fLqNrHSjfeUMkDY2o0k3po',
    appId: '1:761481068514:android:68d32abd655c778d1cc3bb',
    messagingSenderId: '761481068514',
    projectId: 'dimensions-spiralone',
    storageBucket: 'dimensions-spiralone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADu9f53pxCjBc4PcnO7Mr6b75fvR7UBQo',
    appId: '1:761481068514:ios:b75b853f86100b0b1cc3bb',
    messagingSenderId: '761481068514',
    projectId: 'dimensions-spiralone',
    storageBucket: 'dimensions-spiralone.appspot.com',
    iosBundleId: 'com.spiraldimensions.spiralone',
  );
}
